- include: prereq-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tag: pyenv

- include: prereq-Debian.yml
  when: ansible_os_family == 'Debian'

- name: clone pyenv
  git: repo=git://github.com/yyuu/pyenv.git dest={{ PYENV_USER_HOME }}/.pyenv accept_hostkey=yes
  sudo_user: "{{ PYENV_USER }}"

- name: create environ dir
  file: path={{ PYENV_USER_HOME }}/profile.d state=directory mode=0755
  sudo_user: "{{ PYENV_USER }}"

- name: add environ scrip
  copy: src=../files/pyenv.sh dest={{ PYENV_USER_HOME }}/profile.d/ mode=0755
  sudo_user: "{{ PYENV_USER }}"

- name: create {{ PYENV_USER_HOME }}/.zshenv
  file: path={{ PYENV_USER_HOME }}/.zshenv state=file owner={{PYENV_USER}}  mode=0755
  sudo_user: "{{ PYENV_USER }}"

- name: .zshenvでprofile.d/pyenv.shを読み込むように変更
  lineinfile: line='source {{ PYENV_USER_HOME }}/profile.d/pyenv.sh' dest={{ PYENV_USER_HOME }}/.zshenv insertafter=EOF
  sudo_user: "{{ PYENV_USER }}"

- name: python install
  shell: "echo y | '{{ PYENV_USER_HOME }}'/.pyenv/bin/pyenv install {{ PYTHON_VERSION }}"
  sudo_user: "{{ PYENV_USER }}"
  changed_when: false 
  always_run: yes
  
- name: python global 
  shell: "'{{ PYENV_USER_HOME }}'/.pyenv/bin/pyenv global {{ PYTHON_VERSION }}"
  sudo_user: "{{ PYENV_USER }}"
  changed_when: false 
  always_run: yes

- name: clone pyenv-virtualenv
  git: repo=git://github.com/yyuu/pyenv-virtualenv.git dest={{ PYENV_USER_HOME }}/.pyenv/plugins/pyenv-virtualenva accept_hostkey=yes
  sudo_user: "{{ PYENV_USER }}"
